---

- name: Ensure override folder exists
  file:
    dest: /etc/systemd/system/osqueryd.service.d
    state: directory
    mode: '0755'

- name: Enforce cgroups limit on osqueryd
  blockinfile:
    path: /etc/systemd/system/osqueryd.service.d/50-cgroups.conf
    block: |
      [Service]
      CPUShares={{ osquery_cgroups_cpushares | default('100') }}
      CPUQuota={{ osquery_cgroups_cpuquota | default('10%') }}
      MemoryLimit={{ osquery_cgroups_memorylimit | default('1G') }}
    create: true
    backup: true
  notify:
    - reload systemd
    - restart osquery
