---

- name: Debian | download official package
  get_url:
    src: "{{ osquery_deb_url }}"
    dest: "/root/{{ osquery_deb_url | basename }}"
    checksum: "{{ osquery_deb_hash }}"
    mode: '0444'

- name: Debian | install osquery package
  apt:
    deb: "/root/{{ osquery_deb_url | basename }}"
    state: present

