---
# tasks file for osquery

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - osquery

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - osquery

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - osquery
