---
# tasks file for osquery

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - osquery
- name: Include version-specific variables for RedHat
  include_vars: "CentOS-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- include: CentOS.yml
  when: ansible_os_family == "RedHat"
  tags:
    - osquery

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - osquery

- include: Debian.yml
  when: ansible_distribution == "Debian"
  tags:
    - osquery

- block:
    - include: configure.yml
      tags:
        - osquery
        - config

    - name: Enable service
      service: name=osqueryd enabled={{ osquery_service_enable }}
      tags:
        - osquery
        - service
    - name: Start service
      service: name=osqueryd state=started
      when: osquery_service_enable
      tags:
        - osquery
        - service

  when: ansible_os_family == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include: testing.yml
  when: osquery_testing

