---
# tasks file for osquery

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  when: >
    not (ansible_os_family == "RedHat" or ansible_os_family == "Debian")
  tags:
    - osquery

- include: CentOS.yml
  when: ansible_os_family == "RedHat"
  tags:
    - osquery

- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - osquery

- block:
    - name: Install osquery
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ osquery_packages }}"
      tags:
        - osquery
      register: pkg_result
      until: pkg_result is success

    - name: Install osquery debug packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ osquery_debug_packages }}"
      when: osquery_debug_packages_install
      tags:
        - osquery
      register: pkg_result
      until: pkg_result is success

    - include: configure.yml
      tags:
        - osquery
        - config

    - name: Enable service
      service: name=osqueryd enabled={{ osquery_service_enable }}
      tags:
        - osquery
        - service
    - name: Start service
      service: name=osqueryd state=started
      when: osquery_service_enable
      tags:
        - osquery
        - service

    - include: cgroups.yml
      when: osquery_cgroups_restriction_enable

    - include: systemd.yml
      when: osquery_systemd_restriction_enable

    - meta: flush_handlers

    - include: testing.yml
      when: osquery_testing

    - include: profiling.yml
      when: osquery_profiling

    - name: pause a bit to have few queries results
      pause:
        seconds: 80
      when: osquery_testing_pause or osquery_testing

  when: ansible_os_family == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
