---

- block:
    - name: systemd | check service status
      command: "systemctl status osqueryd -l"
      changed_when: false
      register: systemctl
    - debug: var=systemctl.stdout_lines
  when: ansible_service_mgr == "systemd"
- block:
    - name: service | check service status
      command: "service osqueryd status"
      args:
        warn: false
      changed_when: false
      register: service
    - debug: var=service.stdout_lines
  when: ansible_service_mgr != "systemd"

- block:
    - name: ensure directory exists
      file:
        dest: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /tmp/too_many_events
        - /tmp/too_many_events/a
        - /tmp/too_many_events/a/b
        - /tmp/too_many_events2/test
        - /tmp/too_many_events2/a
        - /tmp/too_many_events2/a/b
        - /tmp/too_many_events3/a
        - /tmp/too_many_events3/a/b
        - /tmp/excluded6-testing
        - /var/tmp/a
        - /var/tmp/a/.b
        - /var/tmp/b
        - /var/tmp/b/.c
        - /var/tmp/b/.c/d
        - /a/b/c
  when: osquery_testing_fimfiles or osquery_testing_fim_load

- block:
    - name: create files normally excluded
      file:
        name: "{{ item }}"
        state: touch
      with_items:
        - /tmp/too_many_events2/test/testing-aa
        - /tmp/too_many_events/fim-testing1
        - /tmp/too_many_events/a/fim-testing2
        - /tmp/too_many_events/a/b/fim-testing3
        - /tmp/too_many_events2/fim-testing1
        - /tmp/too_many_events2/a/fim-testing2
        - /tmp/too_many_events2/a/b/fim-testing3
        - /tmp/too_many_events3/fim-testing1
        - /tmp/too_many_events3/a/fim-testing2
        - /tmp/too_many_events3/a/b/fim-testing3
#        - /tmp/excluded1-abcdef
#        - /tmp/abcdef-excluded2
#        - /tmp/excluded3-abcdef-testing
#        - /tmp/excluded4-abcdef-testing-ghijkl-testing-mnopqr
#        - /tmp/excluded5-exact-match
#        - /tmp/excluded6-abcdef
#        - /tmp/excluded6-testing/excluded-abcdef
        - /var/tmp/a/fim-testing1
        - /var/tmp/a/.fim-testing2
        - /var/tmp/a/.b/fim-testing3
        - /var/tmp/b/.fim-testing4
        - /var/tmp/b/.c/fim-testing5
        - /var/tmp/b/.c/d/fim-testing6
        - /a/b/fim-testing10
        - /a/b/c/fim-testing11
    - name: test files
      file:
        name: "{{ item }}"
        state: touch
      with_items: "{{ osquery_testing_fim_files }}"
  when: osquery_testing_fimfiles

- block:
    - name: fallocate big file
      command: "fallocate -l {{ osquery_testing_fim_load_bigger }} /etc/testing-big-file"
      args:
        creates: /etc/testing-big-file
    - name: creation of many small files in excluded directory
      command: "split -b {{ osquery_testing_fim_load_smaller_ex }} /etc/testing-big-file testing-"
      args:
        chdir: /tmp/too_many_events
        creates: /tmp/too_many_events/testing-aa
    - name: clean up
      shell: find /tmp/too_many_events/ -name 'testing-*' -exec rm {} \;
      ignore_errors: true
    - name: creation of many small files
      command: "split -b {{ osquery_testing_fim_load_smaller }} /etc/testing-big-file testing-"
      args:
        chdir: /etc
        creates: /etc/testing-aa
    - name: clean up
      shell: find /etc/ -name 'testing-*' -exec rm {} \;
      ignore_errors: true
# more diverse load? openssl speed, stress...
    - name: retrieve log results
      command: "{{ item }}"
      with_items:
        - head -20 /var/log/osquery/osqueryd.results.log
        - tail -20 /var/log/osquery/osqueryd.results.log
      ignore_errors: true
      changed_when: false
      register: log
  when: osquery_testing_fim_load
