---

- meta: flush_handlers

- name: pause a bit to have few queries results
  pause:
#    minutes: 5
    seconds: 60

- block:
    - name: systemd | check service status
      command: "systemctl status osqueryd -l"
      changed_when: false
      register: systemctl
    - debug: var=systemctl.stdout_lines
  when: ansible_service_mgr == "systemd"
- block:
    - name: service | check service status
      command: "service osqueryd status"
      changed_when: false
      register: service
    - debug: var=service.stdout_lines
  when: ansible_service_mgr != "systemd"
