---
# tasks file for osquery (Ubuntu specific)

- name: Download osquery APT key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C9D8B80B
    state: present
  tags:
    - osquery

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  when: ansible_distribution_release == 'xenial'
  tags:
    - osquery

- name: Configure osquery APT repository
  apt_repository:
    repo: 'deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main'
    state: present
  tags:
    - osquery

- name: Install osquery packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ osquery_packages }}"
  tags:
    - osquery

