---
# handlers file for osquery

- name: restart osquery
  service: name=osqueryd state=restarted sleep=5
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: restart osquery - docker
  service: name=osqueryd state=restarted sleep=5 use=service
  when: (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload osqueryd apparmor profile
  shell: cat /etc/apparmor.d/usr.bin.osqueryd | sudo apparmor_parser -r

- name: reload systemd
  systemd:
    daemon_reload: yes
